### ISSUE TITLE
Does not support new influxdb 2.x client

### ISSUE THREAD

**Issue by cbschuld** [andrewfraley/arris_cable_modem_stats#35]
Hey Andrew:

Current version does not supported the updated 2.x client from Influxdata (https://docs.influxdata.com/influxdb/v2.0/api-guide/client-libraries/python/)

Migration guide here: https://influxdb-client.readthedocs.io/en/stable/migration.html

Breaking Change: the 2.x client requires token based auth so the username/password and a few other options will require adjustment

PR incoming for changes.

**Comment by andrewfraley** [comment]
Added support for InfluxDB 2.x in [release v1.6.0](https://github.com/andrewfraley/arris_cable_modem_stats/releases/tag/v1.6.0).  @cbschuld thanks for the original PR for this.  I implemented it so that we could support both 1.x and 2.x, but used some of your code for arris_stats_influx2.py.  Thanks!
